version: '3'
services:
  universal-csi-driver-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    image: universal-csi-driver-test
    environment:
      ONLINECONF_URI: http://onlineconf-admin
      ONLINECONF_USERNAME: gopher
      ONLINECONF_PASSWORD: gopher
    cap_add:
      - SYS_ADMIN
networks:
  default:
    external:
      name: admin_default
