apiVersion: v1
kind: Secret
metadata:
  name: example-universal-secret
data:
  "username": ...
  "password": ...
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-universal-volume
spec:
  volumeMode: Filesystem
  mountOptions:
    - mode=755
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  csi:
    driver: csi.universal-csi-driver
    volumeHandle: example-universal-volume
    readOnly: true
    volumeAttributes:
      data: {}
    nodeStageSecretRef:
      name: example-universal-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-universal-volume-claim
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  volumeName: example-universal-volume
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
      - name: ...
        ...
        volumeMounts:
        - name: universal-volume
          mountPath: /usr/local/etc/universal
          readOnly: true
      volumes:
      - name: universal-volume
        persistentVolumeClaim:
          claimName: example-universal-volume-claim
